apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-sync
  namespace: color-sync
  labels:
    app: color-sync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color-sync
  template:
    metadata:
      labels:
        app: color-sync
    spec:
      containers:
      - name: color-sync
        image: "REPLACE_WITH_ACR_IMAGE"
        ports:
        - containerPort: 3000
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10