# Configuration for the Prometheus-Grafana Stack
grafana:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: "AK8S"

prometheus:
  prometheusSpec:
    retention: 1d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi