apiVersion: v1
kind: Service
metadata:
  name: color-sync-service
  namespace: color-sync
spec:
  type: LoadBalancer
  selector:
    app: color-sync
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000